---
title: "Data Science with R Workshop Series"
author: "Biostatistics and Data Science Group at Marcus Institute"
output: 
  html_document:
    theme: cosmo
---

This site includes materials for the Data Science with R Workshop Series hosted by Marcus Institute. All the materials are developed by the Biostats and Data Science group at Marcus Institute. We aim to provide trainings to our own group numbers and individuals who are interested in doing data science works using R.

- [Chapter 1 - R Programming Fundamentals](01_getting_started.html)
- [Chapter 2 - Read Data into R](02_data_io.html)
- [Chapter 3 - Data Transformation using Tidyverse](03_data_transformation.html)
- [Chapter 4 - Data Visualization using ggplot2 & plotly](04_data_visualization.html)
- [Chapter 5 - Statistical Models in R](05_modeling.html)
- [Chapter 6 - R Markdown Reports and Tables in Reports](06_rmarkdown.html)
- Chapter 7 - Creating Interactive Web Apps using R Shiny

Chapter 1 - 3 are fundamentals, which you are not recommended to skip. Chapter 4 - 8 don't have to be read in order, although consuming them one by one is still recommended. 

All pages are generated using R Markdown. If you want to see the source R Markdown files, just replace the `.html` with `.Rmd` in the URL.
